{
  ref.set("foo");
  try {
    ref.apply(new FailingFunction());
    fail();
  }
 catch (  WoohaaException expected) {
  }
  assertEquals("foo",ref.get());
}
