{
  final ICompletableFuture<Object> f=putAsyncInternal(key,value,expiryPolicy,false,true);
  try {
    f.get();
  }
 catch (  Throwable e) {
    throw ExceptionUtil.rethrowAllowedTypeFirst(e,CacheException.class);
  }
}
