{
  RuntimeException expectedEx=null;
  try {
    service.putUsingSameBean_thenOtherBeanThrowingException_sameTransaction(new DummyObject(1L,"magic"),new DummyObject(2L,"magic2"));
  }
 catch (  RuntimeException ex) {
    expectedEx=ex;
  }
 finally {
    Assert.assertNotNull(expectedEx);
    Assert.assertEquals(0L,instance.getMap("dummyObjectMap").size());
  }
}
