{
  if (obj == null) {
    return NULL_RESPONSE;
  }
  Throwable error=getError(obj);
  if (error == null) {
    return obj;
  }
  ExceptionAction action=onException(error);
  int localInvokeCount=invokeCount;
  if (action == ExceptionAction.RETRY_INVOCATION && localInvokeCount < tryCount) {
    if (localInvokeCount > LOG_MAX_INVOCATION_COUNT && localInvokeCount % LOG_INVOCATION_COUNT_MOD == 0) {
      logger.warning("Retrying invocation: " + toString() + ", Reason: "+ error);
    }
    return RETRY_RESPONSE;
  }
  if (action == ExceptionAction.CONTINUE_WAIT) {
    return WAIT_RESPONSE;
  }
  return error;
}
