{
  assertTerminates();
  assertNotNull("an error should have been thrown, but " + getName() + " completed without error",error);
  assertTrue("error instanceof " + error,error.getClass().isAssignableFrom(cause));
}
