{
  try {
    return getContext().getInvocationService().invokeOnRandomTarget(request);
  }
 catch (  Exception e) {
    throw ExceptionUtil.rethrow(e);
  }
}
