{
  try {
    processTaskAndSendResponse(taskId,task);
  }
 catch (  Exception e) {
    logger.warning("Problem while handling task: " + task,e);
  }
}
