{
  try {
    final Future<T> future=getContext().getInvocationService().invokeOnRandomTarget(request);
    return future.get();
  }
 catch (  Exception e) {
    throw ExceptionUtil.rethrow(e);
  }
}
