{
  CancellationAwareTask task=new CancellationAwareTask(10000);
  ExecutorService executor=Hazelcast.getExecutorService();
  Future future=executor.submit(task);
  try {
    future.get(2,TimeUnit.SECONDS);
    fail("Should throw TimeoutException!");
  }
 catch (  TimeoutException expected) {
  }
catch (  Exception e) {
    fail("No other Exception!!");
  }
  assertFalse(future.isDone());
  assertTrue(future.cancel(true));
  assertTrue(future.isCancelled());
  try {
    future.get();
    fail("Should not complete the task successfully");
  }
 catch (  CancellationException e) {
  }
catch (  Exception e) {
    fail("Unexpected exception " + e.getMessage());
  }
}
