{
  try {
    doRun();
  }
 catch (  Exception e) {
    error=e;
  }
}
