{
  ref.set("foo");
  try {
    ref.alter(new FailingFunction());
    fail();
  }
 catch (  ExpectedRuntimeException expected) {
  }
  assertEquals("foo",ref.get());
}
